spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/image
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG